@baseUrl = http://localhost:8080/api
@missionId = mission-self-introduction-card
@firebaseUid = 0BvPVYjYhZbEhbvtVV11VcFhNV63

### Get mission overview
GET {{baseUrl}}/missions/{{missionId}}/overview
X-Dev-Firebase-Uid: {{firebaseUid}}