ALTER TYPE "CourseCategoryType" ADD VALUE IF NOT EXISTS 'SORT';
ALTER TYPE "CourseCategoryType" ADD VALUE IF NOT EXISTS 'SEARCH';
ALTER TYPE "CourseCategoryType" ADD VALUE IF NOT EXISTS 'GRAPH';
ALTER TYPE "CourseCategoryType" ADD VALUE IF NOT EXISTS 'DATA_STRUCTURE';
ALTER TYPE "CourseCategoryType" ADD VALUE IF NOT EXISTS 'DYNAMIC_PROGRAMMING';
