import {
  AchievementCategory,
  AchievementConditionType,
  type Prisma,
} from "@prisma/client";

const course1Id = "course-web-overview";

export const achievementSeed: Prisma.AchievementUncheckedCreateInput[] = [
  {
    id: "ach-bubble-sort-complete",
    category: AchievementCategory.COURSE_COMPLETE,
    conditionType: AchievementConditionType.COURSE_REQUIRED_MISSION_COMPLETE,
    courseId: "course-algorithm-bubble-sort-v2",
    title: "バブルソートを理解した",
    description: "比較・交換・確定済み領域をたどり、バブルソートのコース完了課題を達成した証です。",
    isSecret: false,
    sortOrder: 5,
  },
  {
    id: "ach-first-mission-clear",
    category: AchievementCategory.MISSION_CLEAR,
    conditionType: AchievementConditionType.MISSION_COUNT,
    conditionValue: 1,
    title: "はじめての一歩",
    description: "はじめてミッションをクリアした証です。",
    isSecret: false,
    sortOrder: 10,
  },
  {
    id: "ach-mission-clear-lv1",
    category: AchievementCategory.MISSION_COUNT,
    conditionType: AchievementConditionType.MISSION_COUNT,
    conditionValue: 3,
    title: "ミッション挑戦者 Lv.1",
    description: "3個のミッションをクリアした証です。",
    isSecret: false,
    sortOrder: 20,
  },
  {
    id: "ach-mission-clear-lv2",
    category: AchievementCategory.MISSION_COUNT,
    conditionType: AchievementConditionType.MISSION_COUNT,
    conditionValue: 5,
    title: "ミッション挑戦者 Lv.2",
    description: "5個のミッションをクリアした証です。",
    isSecret: false,
    sortOrder: 30,
  },
  {
    id: "ach-mission-clear-lv3",
    category: AchievementCategory.MISSION_COUNT,
    conditionType: AchievementConditionType.MISSION_COUNT,
    conditionValue: 10,
    title: "ミッション挑戦者 Lv.3",
    description: "10個のミッションをクリアした証です。",
    isSecret: false,
    sortOrder: 40,
  },
  {
    id: "ach-course1-required-complete",
    category: AchievementCategory.COURSE_COMPLETE,
    conditionType: AchievementConditionType.COURSE_REQUIRED_MISSION_COMPLETE,
    courseId: course1Id,
    title: "Webアプリの見取り図を手に入れた",
    description:
      "Webアプリの基本的な流れと構成要素を理解した証です。",
    isSecret: false,
    sortOrder: 50,
  },
  {
    id: "ach-course1-all-complete",
    category: AchievementCategory.COURSE_COMPLETE,
    conditionType: AchievementConditionType.COURSE_ALL_MISSION_COMPLETE,
    courseId: course1Id,
    title: "Webアプリ探索マスター",
    description:
      "Course1のすべてのミッションをクリアし、Webアプリの全体像を深く探索した証です。",
    isSecret: false,
    sortOrder: 60,
  },
  {
    id: "ach-course1-exam-hard-clear",
    category: AchievementCategory.COURSE_EXAM,
    conditionType: AchievementConditionType.COURSE_EXAM_HARD_CLEAR,
    courseId: course1Id,
    title: "Webアプリ全体像 Hardクリア",
    description:
      "Webアプリの全体像コース完了ミッションを、むずかしい難易度でクリアした証です。",
    isSecret: false,
    sortOrder: 65,
  },
  {
    id: "ach-activity-clear-lv1",
    category: AchievementCategory.LEARNING_ACTION,
    conditionType: AchievementConditionType.ACTIVITY_COUNT,
    conditionValue: 10,
    title: "学習ステップ Lv.1",
    description: "10個のアクティビティを完了した証です。",
    isSecret: false,
    sortOrder: 70,
  },
  {
    id: "ach-activity-clear-lv2",
    category: AchievementCategory.LEARNING_ACTION,
    conditionType: AchievementConditionType.ACTIVITY_COUNT,
    conditionValue: 30,
    title: "学習ステップ Lv.2",
    description: "30個のアクティビティを完了した証です。",
    isSecret: false,
    sortOrder: 80,
  },
  {
    id: "ach-activity-clear-lv3",
    category: AchievementCategory.LEARNING_ACTION,
    conditionType: AchievementConditionType.ACTIVITY_COUNT,
    conditionValue: 50,
    title: "学習ステップ Lv.3",
    description: "50個のアクティビティを完了した証です。",
    isSecret: false,
    sortOrder: 90,
  },
  {
    id: "ach-streak-lv1",
    category: AchievementCategory.STREAK,
    conditionType: AchievementConditionType.STREAK_DAYS,
    conditionValue: 2,
    title: "学習リズム Lv.1",
    description: "2日連続で学習した証です。",
    isSecret: false,
    sortOrder: 100,
  },
  {
    id: "ach-streak-lv2",
    category: AchievementCategory.STREAK,
    conditionType: AchievementConditionType.STREAK_DAYS,
    conditionValue: 3,
    title: "学習リズム Lv.2",
    description: "3日連続で学習した証です。",
    isSecret: false,
    sortOrder: 110,
  },
  {
    id: "ach-streak-lv3",
    category: AchievementCategory.STREAK,
    conditionType: AchievementConditionType.STREAK_DAYS,
    conditionValue: 7,
    title: "学習リズム Lv.3",
    description: "7日連続で学習した証です。",
    isSecret: false,
    sortOrder: 120,
  },
];
