import { TechIconBadgeRarity, type Prisma } from "@prisma/client";

export const badgeSeed: Prisma.TechIconBadgeUncheckedCreateInput[] = [
  {
    id: "badge-html",
    name: "HTML",
    description: "Webページの構造を作るための基本技術です。",
    iconUrl: "/images/badges/html.png",
    rarity: TechIconBadgeRarity.COMMON,
    sortOrder: 10,
    isPublished: true,
  },
  {
    id: "badge-css",
    name: "CSS",
    description: "Webページの見た目やレイアウトを整えるための技術です。",
    iconUrl: "/images/badges/css.png",
    rarity: TechIconBadgeRarity.COMMON,
    sortOrder: 20,
    isPublished: true,
  },
  {
    id: "badge-javascript",
    name: "JavaScript",
    description: "Webページに動きや処理を加えるためのプログラミング言語です。",
    iconUrl: "/images/badges/javascript.png",
    rarity: TechIconBadgeRarity.COMMON,
    sortOrder: 30,
    isPublished: true,
  },
  {
    id: "badge-python",
    name: "Python",
    description: "Web開発、データ処理、AIなど幅広く使われる言語です。",
    iconUrl: "/images/badges/python.png",
    rarity: TechIconBadgeRarity.COMMON,
    sortOrder: 40,
    isPublished: true,
  },
  {
    id: "badge-flask",
    name: "Flask",
    description: "Pythonで軽量なWebアプリを作るためのフレームワークです。",
    iconUrl: "/images/badges/flask.png",
    rarity: TechIconBadgeRarity.RARE,
    sortOrder: 50,
    isPublished: true,
  },
  {
    id: "badge-database",
    name: "Database",
    description: "アプリで使うデータを保存し、あとから取り出すための仕組みです。",
    iconUrl: "/images/badges/database.png",
    rarity: TechIconBadgeRarity.RARE,
    sortOrder: 60,
    isPublished: true,
  },
  {
    id: "badge-api",
    name: "API",
    description: "アプリやサービス同士がデータや機能をやり取りするための入口です。",
    iconUrl: "/images/badges/api.png",
    rarity: TechIconBadgeRarity.RARE,
    sortOrder: 70,
    isPublished: true,
  },
  {
    id: "badge-cloud-firebase",
    name: "Firebase",
    description: "認証、ホスティング、データ保存などを扱えるクラウドサービスです。",
    iconUrl: "/images/badges/firebase.png",
    rarity: TechIconBadgeRarity.RARE,
    sortOrder: 80,
    isPublished: true,
  },
  {
    id: "badge-cloud-vercel",
    name: "Vercel",
    description: "Webアプリを公開しやすいクラウドプラットフォームです。",
    iconUrl: "/images/badges/vercel.png",
    rarity: TechIconBadgeRarity.RARE,
    sortOrder: 90,
    isPublished: true,
  },
  {
    id: "badge-cloud-docker",
    name: "Docker",
    description: "アプリの実行環境をコンテナとして扱うための技術です。",
    iconUrl: "/images/badges/docker.png",
    rarity: TechIconBadgeRarity.RARE,
    sortOrder: 100,
    isPublished: true,
  },
  {
    id: "badge-cloud-aws",
    name: "AWS",
    description: "サーバ、DB、AIなど多くの機能を提供するクラウドサービス群です。",
    iconUrl: "/images/badges/aws.png",
    rarity: TechIconBadgeRarity.EPIC,
    sortOrder: 110,
    isPublished: true,
  },
  {
    id: "badge-cloud-google-cloud",
    name: "Google Cloud",
    description: "アプリ公開、データ分析、AIなどを扱えるクラウドサービス群です。",
    iconUrl: "/images/badges/google-cloud.png",
    rarity: TechIconBadgeRarity.EPIC,
    sortOrder: 120,
    isPublished: true,
  },
  {
    id: "badge-cloud-azure",
    name: "Azure",
    description: "Microsoftが提供するクラウドサービス群です。",
    iconUrl: "/images/badges/azure.png",
    rarity: TechIconBadgeRarity.EPIC,
    sortOrder: 130,
    isPublished: true,
  },
];
