import {
  CourseCategoryType,
  CourseDifficulty,
  MissionActivityType,
  MissionType,
} from "@prisma/client";
import type {
  CourseSeed,
  MissionSeed,
} from "./learningSeedTypes";

const missionOne: MissionSeed = {
  id: "algorithm-v2-bubble-sort-purpose",
  title: "バブルソートを知ろう",
  description: "データを並べ替えるソートの目的、利用場面、代表的な方法を知り、このコースで学ぶ内容を確認します。",
  difficulty: CourseDifficulty.EASY,
  goalImg: "/images/missions/web-flow.png",
  estimatedMinutes: 6,
  order: 1,
  type: MissionType.MAIN,
  isRequiredForCourseCompletion: true,
  parentMissionId: null,
  roadmapLane: 0,
  branchOrder: 0,
  rewardExp: 60,
  learnedItems: ["ソートが解決する問題", "ソートが使われる場面", "代表的なソートアルゴリズム", "このコースの学習順序"],
  isPublished: true,
  activities: [
    {
      id: "algorithm-v2-bubble-sort-purpose-experience-sort",
      type: MissionActivityType.VIEW,
      title: "ソートとは何か",
      instruction: "並べ替え前と並べ替え後のデータを見ながら、ソートがどのような処理なのか確認しましょう。",
      mentorMessage: "まずは、アルゴリズムを学ぶ前に「何をする処理なのか」をつかもう。",
      content: {
        learningRole: "ORIENTATION",
        rendererKey: "SORT_OVERVIEW",
        feedbackPolicy: { mode: "NONE" },
        data: {
          body: "",
          explanation: "ソートとは、複数のデータを決められた順序に並べ替える処理です。\n\n数値を小さい順に並べることを「昇順」、大きい順に並べることを「降順」といいます。",
          beforeValues: [5, 2, 4, 1],
          ascendingValues: [1, 2, 4, 5],
          descendingValues: [5, 4, 2, 1],
          finalExplanation: "このコースでは、数値を小さい順に並べる「昇順」のバブルソートを学びます。",
        },
      },
      preview: null,
      actionLabel: "次へ",
      order: 1,
    },
    {
      id: "algorithm-v2-bubble-sort-purpose-use-cases",
      type: MissionActivityType.VIEW,
      title: "ソートはどこで使われる？",
      instruction: "データを決まった順序へ並べる処理が、身近なサービスでどのように使われるか確認しましょう。",
      mentorMessage: "見やすい順序に並んでいると、たくさんのデータからでも必要なものを見つけやすいね。",
      content: {
        learningRole: "ORIENTATION",
        rendererKey: "TEXT",
        feedbackPolicy: { mode: "NONE" },
        data: {
          body: "ソートは、商品を価格の安い順に表示したり、ランキングを得点の高い順に並べたり、予定を日時の早い順に表示したりする場面で使われます。\n\nデータの順序を整えることで、一覧を比べやすくし、目的の情報を扱いやすくできます。",
          sections: [
            { heading: "商品一覧", body: "価格の安い順・高い順に並べる" },
            { heading: "ランキング", body: "得点や記録の高い順に並べる" },
            { heading: "予定や履歴", body: "日時の新しい順・古い順に並べる" },
          ],
          conclusion: "多くのデータを扱うサービスでは、目的に合った順序へデータを整えるためにソートが使われています。",
        },
      },
      preview: null,
      actionLabel: "次へ",
      order: 2,
    },
    {
      id: "algorithm-v2-bubble-sort-purpose-related-algorithms",
      type: MissionActivityType.VIEW,
      title: "いろいろなソート方法",
      instruction: "並べ替え方には複数の方法があり、データの特徴や目的に応じて使い分けられることを知りましょう。",
      mentorMessage: "同じ並べ替えでも方法はいろいろあるんだね。今回は動きを追いやすいバブルソートに注目しよう！",
      content: {
        learningRole: "ORIENTATION",
        rendererKey: "TEXT",
        feedbackPolicy: { mode: "NONE" },
        data: {
          body: "ソートアルゴリズムには、それぞれ異なる並べ替え方があります。",
          comparison: {
            headers: ["ソート方法", "並べ替え方"],
            rows: [
              { cells: ["バブルソート", "隣り合う値を比べて交換する"], label: "このコースで学習" },
              { cells: ["選択ソート", "最小の値を探して先頭から確定する"] },
              { cells: ["挿入ソート", "値を整列済みの部分へ差し込む"] },
            ],
          },
          conclusion: "このコースでは、比較と交換の動きを追いながら、バブルソートとPythonコードの対応を学びます。",
        },
      },
      preview: null,
      actionLabel: "次へ",
      order: 3,
    },
    {
      id: "algorithm-v2-bubble-sort-purpose-course-roadmap",
      type: MissionActivityType.VIEW,
      title: "このコースで学ぶこと",
      instruction: "これからどのような順序でバブルソートを学ぶのか、学習の流れを確認しましょう。",
      mentorMessage: "一度にすべてのコードを覚えなくて大丈夫。処理を一つずつ理解して、最後に組み合わせよう。",
      content: {
        learningRole: "ORIENTATION",
        rendererKey: "LEARNING_ROADMAP",
        feedbackPolicy: { mode: "NONE" },
        data: {
          body: "このコースでは、Pythonのリスト、変数、if文、for文、len、rangeを知っていることを前提にします。比較・交換・繰り返しを動きと対応づけ、最後に既習コードを組み合わせます。",
          roadmapSteps: [
          "ソートとバブルソートを知る",
          "隣り合う値を比較・交換する",
          "比較を右端まで繰り返す",
          "一周分の処理を繰り返す",
          "比較範囲を短くする",
          "バブルソートのコードを完成させる",
          "バブルソートを自分で実装する",
          ],
          emphasis: "コースのゴールは、バブルソートの動きを説明し、Pythonで自分で実装できるようになることです。",
        },
      },
      preview: null,
      actionLabel: "Missionを完了",
      order: 4,
    },
  ],
};

const missionTwo: MissionSeed = {
  id: "algorithm-v2-bubble-sort-basic",
  title: "隣り合う値を比較・交換しよう",
  description: "バブルソートでは、隣り合う2つの値を比較し、左の値が大きい場合に交換します。このMissionでは、交換が必要になる条件と、その判断・交換処理をPythonコードで表す方法を学びます。",
  difficulty: CourseDifficulty.EASY,
  goalImg: "/images/missions/web-flow.png",
  estimatedMinutes: 16,
  order: 2,
  type: MissionType.MAIN,
  isRequiredForCourseCompletion: true,
  parentMissionId: null,
  roadmapLane: 0,
  branchOrder: 0,
  rewardExp: 160,
  learnedItems: ["左の値が大きいときに交換する", "Pythonの比較演算子", "Pythonの同時代入", "比較と交換をif文で組み合わせる"],
  isPublished: true,
  activities: [
    {
      id: "algorithm-v2-bubble-sort-basic-rule-v2",
      type: MissionActivityType.VIEW,
      title: "比較と交換のルールを知ろう",
      instruction: "隣り合う2つの値を見ながら、バブルソートで交換が行われる条件を確認しましょう。",
      mentorMessage: "昇順では、小さい値が左側、大きい値が右側になるように並べるよ。",
      content: {
        learningRole: "EXPLANATION",
        rendererKey: "COMPARISON_RULE",
        feedbackPolicy: { mode: "NONE" },
        data: {
          explanation: "バブルソートでは、隣り合う2つの値を比較します。数値を小さい順に並べる場合、左の値が右の値より大きければ交換し、右の値以下なら交換しません。",
          rule: "左の値 ＞ 右の値の場合に交換する",
          examples: [
            { title: "例1：交換が必要", before: [6, 3], after: [3, 6], description: "左の6は右の3より大きいため、2つの値を交換します。", didSwap: true },
            { title: "例2：交換は不要", before: [2, 5], after: [2, 5], description: "左の2は右の5より小さく、すでに昇順なので交換しません。", didSwap: false },
          ],
        },
      },
      preview: null,
      actionLabel: "次へ",
      order: 1,
    },
    {
      id: "algorithm-v2-bubble-sort-basic-decisions-v2",
      type: MissionActivityType.SELECT_FILL,
      title: "交換が必要な組を判断しよう",
      instruction: "それぞれの値の組について、昇順に並べるために交換が必要かどうかを選んでください。",
      mentorMessage: "左と右を見比べて、小さい値が左に来ているか確認しよう。",
      content: {
        learningRole: "GUIDED_PRACTICE",
        rendererKey: "PAIR_DECISION",
        feedbackPolicy: { mode: "RETRY_WITH_HINT", revealAfterAttempts: 2 },
        data: {
          question: "表示された組について、交換するかどうかを選んでください",
          values: [6, 3, 5, 2],
          decisionPairs: [
          { id: "pair-1", left: 6, right: 3, feedback: "左の6が右の3より大きいため、交換が必要です。" },
          { id: "pair-2", left: 2, right: 5, feedback: "左の2が右の5より小さく、すでに昇順になっています。" },
          { id: "pair-3", left: 4, right: 4, feedback: "2つの値は同じなので、交換する必要はありません。" },
          { id: "pair-4", left: 7, right: 1, feedback: "左の7が右の1より大きいため、交換が必要です。" },
          ],
          correctAnswers: { "pair-1": "swap", "pair-2": "keep", "pair-3": "keep", "pair-4": "swap" },
          correctFeedback: "交換が必要になる条件を判断できました。昇順では、左の値が右の値より大きい場合だけ交換します。",
          incorrectFeedback: "小さい値が左側になるように並べることを考えてみよう。",
          completionLabel: "次へ",
        },
      },
      preview: null,
      actionLabel: "答えを確認する",
      order: 2,
    },
    {
      id: "algorithm-v2-bubble-sort-basic-python-condition-v2",
      type: MissionActivityType.VIEW,
      title: "比較条件をPythonで表そう",
      instruction: "交換が必要になる条件を、Pythonコードでどのように表すか確認しましょう。",
      mentorMessage: "Pythonでは、2つの値の大小関係を比較演算子で表すよ。",
      content: {
        learningRole: "CODE_MAPPING",
        rendererKey: "PYTHON_COMPARISON",
        feedbackPolicy: { mode: "NONE" },
        data: {
          values: [6, 3, 5, 2],
          comparisonCode: "numbers[0] > numbers[1]",
          explanation: "> は、左側の値が右側の値より大きいかを調べる比較演算子です。今回の6 > 3はTrueになります。",
        },
      },
      preview: null,
      actionLabel: "次へ",
      order: 3,
    },
    {
      id: "algorithm-v2-bubble-sort-basic-condition-fill-v2",
      type: MissionActivityType.SELECT_FILL,
      title: "比較条件を完成させよう",
      instruction: "左の値が右の値より大きい場合に条件が成立するように、比較演算子を選んでください。",
      mentorMessage: "どの記号なら『左が大きい』を表せるかな？",
      content: {
        learningRole: "CODE_MAPPING",
        rendererKey: "CONDITION_FILL",
        feedbackPolicy: { mode: "RETRY_WITH_HINT", revealAfterAttempts: 2 },
        data: {
          values: [6, 3, 5, 2],
          question: "空欄に入る比較演算子を選んでください",
          optionFill: true,
          fillOptions: [
          { id: "less", label: "<" },
          { id: "greater", label: ">" },
          { id: "equal", label: "==" },
          { id: "not-equal", label: "!=" },
          ],
          correctAnswers: "greater",
          optionFeedback: {
          less: "< では、左の値が小さいときに条件が成立します。今回は左側に大きい値がある場合を判断します。",
          equal: "== は、2つの値が同じかどうかを調べます。今回はどちらの値が大きいかを判断します。",
          "not-equal": "!= は、2つの値が異なるかを調べます。異なるだけでは交換が必要か判断できません。",
          },
          correctFeedback: "正解です。左の6が右の3より大きいため条件はTrueになり、昇順では2つの値を交換します。",
          completionLabel: "次へ",
        },
      },
      preview: null,
      actionLabel: "答えを確認する",
      order: 4,
    },
    {
      id: "algorithm-v2-bubble-sort-basic-python-swap-v2",
      type: MissionActivityType.VIEW,
      title: "2つの値をPythonで交換しよう",
      instruction: "Pythonで、配列内の2つの値を入れ替える方法を確認しましょう。",
      mentorMessage: "Pythonなら、一時変数を作らなくても1行で交換できるよ。",
      content: {
        learningRole: "CODE_MAPPING",
        rendererKey: "PYTHON_SWAP",
        feedbackPolicy: { mode: "NONE" },
        data: {
          values: [6, 3, 5, 2],
          swapCode: "numbers[0], numbers[1] = numbers[1], numbers[0]",
          resultValues: [3, 6, 5, 2],
        },
      },
      preview: null,
      actionLabel: "次へ",
      order: 5,
    },
    {
      id: "algorithm-v2-bubble-sort-basic-swap-fill-v2",
      type: MissionActivityType.SELECT_FILL,
      title: "交換コードを完成させよう",
      instruction: "位置0と位置1の値を交換するように、コードの空欄を完成させてください。",
      mentorMessage: "それぞれの位置に、交換前とは反対側の値を代入しよう。",
      content: {
        learningRole: "CODE_MAPPING",
        rendererKey: "SWAP_FILL",
        feedbackPolicy: { mode: "RETRY_WITH_HINT", revealAfterAttempts: 2 },
        data: {
          values: [6, 3, 5, 2],
          question: "右辺へ入れる値の順番を選んでください",
          optionFill: true,
          fillOptions: [
          { id: "same", label: "numbers[0], numbers[1]" },
          { id: "reverse", label: "numbers[1], numbers[0]" },
          { id: "left-only", label: "numbers[0], numbers[0]" },
          { id: "right-only", label: "numbers[1], numbers[1]" },
          ],
          correctAnswers: "reverse",
          correctFeedback: "正解です。右側の値を反対の位置へ代入し、位置0と位置1の値を交換できました。交換後は[3, 6, 5, 2]です。",
          incorrectFeedback: "交換後は位置0に3、位置1に6が入ります。右辺に並べる値の順番を確認してください。",
          completionLabel: "次へ",
        },
      },
      preview: null,
      actionLabel: "答えを確認する",
      order: 6,
    },
    {
      id: "algorithm-v2-bubble-sort-basic-if-swap-build-v2",
      type: MissionActivityType.SELECT_FILL,
      title: "比較と交換の処理を完成させよう",
      instruction: "昇順になるように、比較条件と交換処理を正しい順番と階層に並べてください。",
      mentorMessage: "まず交換が必要か判断して、条件が成立したときだけ交換しよう。",
      content: {
        learningRole: "INDEPENDENT_PRACTICE",
        rendererKey: "IF_SWAP_BUILD",
        feedbackPolicy: { mode: "RETRY_WITH_HINT", revealAfterAttempts: 2 },
        data: {
          values: [6, 3, 5, 2],
          question: "比較条件を上段、交換処理をif文の内側へ配置してください",
          codeBlockBuilder: true,
          codeBlocks: [
          { id: "condition-greater", label: "if numbers[0] > numbers[1]:" },
          { id: "swap-values", label: "numbers[0], numbers[1] = numbers[1], numbers[0]" },
          { id: "condition-less", label: "if numbers[0] < numbers[1]:", feedback: "昇順では、左の値が右の値より大きい場合に交換します。比較演算子を確認してください。" },
          { id: "keep-values", label: "numbers[0], numbers[1] = numbers[0], numbers[1]", feedback: "交換後は、2つの値が反対の位置へ移動します。右辺の順番を確認してください。" },
          { id: "copy-left", label: "numbers[0] = numbers[1]", feedback: "片方へ代入するだけでは2つの値を交換できません。両方の位置へ反対側の値を代入してください。" },
          ],
          correctAnswers: ["condition-greater", "swap-values"],
          correctFeedback: "Mission 2クリア！ 隣り合う2つの値を比較し、左の値が大きい場合だけ交換する処理をPythonで表すことができました。次のMissionでは、比較位置を右へ動かして右端まで繰り返します。",
          incorrectFeedback: "比較条件を先に置き、交換処理をif文の内側へ配置してください。",
          completionLabel: "Missionを完了",
        },
      },
      preview: null,
      actionLabel: "コードを実行する",
      order: 7,
    },
  ],
};

const missionThree: MissionSeed = {
  id: "algorithm-v2-bubble-sort-one-pass",
  title: "比較を右端まで繰り返そう",
  description: "前のMissionで学んだ比較と交換を、比較位置を右へ動かしながら繰り返し、配列を一周するコードを作ります。",
  difficulty: CourseDifficulty.EASY,
  goalImg: "/images/missions/web-flow.png",
  estimatedMinutes: 16,
  order: 3,
  type: MissionType.MAIN,
  isRequiredForCourseCompletion: true,
  parentMissionId: null,
  roadmapLane: 0,
  branchOrder: 0,
  rewardExp: 160,
  learnedItems: ["比較位置を左から右へ動かす", "比較位置をjで表す", "隣り合う値をnumbers[j]とnumbers[j + 1]で表す", "n個の要素にはn - 1組の隣接ペアがある", "for文で一周分の処理を作る", "一周後に最大値が右端へ移動する"],
  isPublished: true,
  activities: [
    {
      id: "algorithm-v2-bubble-sort-one-pass-move-comparison-v2",
      type: MissionActivityType.VIEW,
      title: "比較する位置を右へ動かそう",
      instruction: "配列の中で、比較する2つの値がどのように右へ移動するか確認しましょう。",
      mentorMessage: "さっき作った比較と交換を、今度は右へずらしながら続けていくよ！",
      content: {
        learningRole: "EXPLANATION",
        rendererKey: "ARRAY_TRACE",
        feedbackPolicy: { mode: "NONE" },
        data: {
          values: [5, 2, 4, 1],
          body: "バブルソートでは、最初の2つの値だけを比較して終わりではありません。比較する位置を1つずつ右へ動かしながら、隣り合う値の比較と交換を繰り返します。",
          intervalMs: 1100,
          steps: [
            {
              comparingIndices: [0, 1],
              pointers: [{ index: 0, label: "比較位置" }],
              message: "最初は、位置0と位置1の隣り合う値を比較します。",
            },
            {
              comparingIndices: [1, 2],
              pointers: [{ index: 1, label: "比較位置" }],
              message: "比較する位置を1つ右へ動かし、位置1と位置2を比較します。",
            },
            {
              comparingIndices: [2, 3],
              pointers: [{ index: 2, label: "比較位置" }],
              message: "さらに1つ右へ動かし、位置2と位置3を比較します。",
            },
          ],
          finalMessage: "4つの値がある場合、隣り合う値の組は3組あります。そのため、一周では3回の比較を行います。",
        },
      },
      preview: null,
      actionLabel: "次へ",
      order: 1,
    },
    {
      id: "algorithm-v2-bubble-sort-one-pass-next-pair-v2",
      type: MissionActivityType.SELECT_FILL,
      title: "次に比較する組を選ぼう",
      instruction: "現在比較している位置を見ながら、次に比較する2つの値を選んでください。",
      mentorMessage: "比較が終わったら、そのまま1つ右へ進めばOKだよ！",
      content: {
        learningRole: "GUIDED_PRACTICE",
        rendererKey: "NEXT_PAIR_SEQUENCE",
        feedbackPolicy: { mode: "RETRY_WITH_HINT", revealAfterAttempts: 2 },
        data: {
          values: [6, 3, 5, 2],
          comparisonSequence: true,
          sequenceQuestions: [
          {
          currentPair: [0, 1],
          question: "次に比較する組を選んでください。",
          options: [
          { id: "pair-0-1", label: "位置0と位置1（6と3）" },
          { id: "pair-1-2", label: "位置1と位置2（3と5）" },
          { id: "pair-2-3", label: "位置2と位置3（5と2）" },
          ],
          afterMessage: "位置を1つ右へ動かしたので、次は位置1と位置2を比較します。",
          },
          {
          currentPair: [1, 2],
          question: "次に比較する組を選んでください。",
          options: [
          { id: "pair-0-1", label: "位置0と位置1（6と3）" },
          { id: "pair-1-2", label: "位置1と位置2（3と5）" },
          { id: "pair-2-3", label: "位置2と位置3（5と2）" },
          ],
          afterMessage: "さらに1つ右へ動かし、位置2と位置3を比較します。",
          },
          {
          currentPair: [2, 3],
          question: "この比較が終わった後、さらに右側に比較できる組はありますか？",
          options: [
          { id: "yes", label: "ある" },
          { id: "no", label: "ない" },
          ],
          afterMessage: "位置3は配列の右端なので、これ以上右側に比較できる組はありません。これで一周分の比較が終わります。",
          },
          ],
          correctAnswers: ["pair-1-2", "pair-2-3", "no"],
          correctFeedback: "正解です。比較位置を1つずつ右へ動かし、配列の右端まで確認できました。",
          incorrectFeedback: "現在の比較位置から、1つ右へずらした2つの値を探してみよう。",
          completionLabel: "次へ",
        },
      },
      preview: null,
      actionLabel: "答えを確認する",
      order: 2,
    },
    {
      id: "algorithm-v2-bubble-sort-one-pass-j-mapping-v2",
      type: MissionActivityType.VIEW,
      title: "比較する位置をjで表そう",
      instruction: "比較する位置が変わっても同じコードを使えるように、位置を変数で表す方法を確認しましょう。",
      mentorMessage: "毎回0や1を書き直す代わりに、比較する位置をjに任せよう！",
      content: {
        learningRole: "CODE_MAPPING",
        rendererKey: "J_POSITION_MAPPING",
        feedbackPolicy: { mode: "NONE" },
        data: {
          values: [6, 3, 5, 2],
          body: "左側の比較位置を変数jで表すと、隣り合う2つの値をnumbers[j]とnumbers[j + 1]で指定できます。",
          mappings: [
          { j: 0, pair: [0, 1] },
          { j: 1, pair: [1, 2] },
          { j: 2, pair: [2, 3] },
          ],
          emphasis: "jが1増えると、比較する2つの位置も1つ右へ移動します。",
        },
      },
      preview: null,
      actionLabel: "次へ",
      order: 3,
    },
    {
      id: "algorithm-v2-bubble-sort-one-pass-j-choice-v2",
      type: MissionActivityType.CHOICE,
      title: "jが表す比較位置を確認しよう",
      instruction: "jの値を確認し、コードが比較する2つの値を選んでください。",
      mentorMessage: "numbers[j]とnumbers[j + 1]が、配列のどこを指しているか追ってみよう！",
      content: {
        learningRole: "GUIDED_PRACTICE",
        rendererKey: "J_PAIR_CHOICE",
        feedbackPolicy: { mode: "RETRY_WITH_HINT", revealAfterAttempts: 2 },
        data: {
          values: [7, 2, 6, 4],
          j: 1,
          code: "numbers[j] > numbers[j + 1]",
          question: "このコードが比較する2つの値を選んでください。",
          choices: [
          { id: "pair-7-2", label: "7と2", isCorrect: false, feedback: "jを1へ置き換えてみよう。numbers[j]はnumbers[1]、numbers[j + 1]はnumbers[2]になるよ。" },
          { id: "pair-2-6", label: "2と6", isCorrect: true, feedback: "正解です。j = 1なので、左側は位置1、右側は位置2です。numbers[1] > numbers[2]、つまり2 > 6を確認します。" },
          { id: "pair-6-4", label: "6と4", isCorrect: false, feedback: "6と4はj = 2のときの組だよ。今回はj = 1を添字へ置き換えよう。" },
          { id: "pair-7-6", label: "7と6", isCorrect: false, feedback: "numbers[j]とnumbers[j + 1]は必ず隣り合う位置を指すよ。" },
          ],
          completionLabel: "次へ",
        },
      },
      preview: null,
      actionLabel: "答えを確認する",
      order: 4,
    },
    {
      id: "algorithm-v2-bubble-sort-one-pass-loop-v2",
      type: MissionActivityType.VIEW,
      title: "一周分の繰り返しをコードで表そう",
      instruction: "比較する位置を自動的に右へ動かすfor文を確認しましょう。",
      mentorMessage: "for文に任せれば、jを0、1、2と順番に動かせるよ！",
      content: {
        learningRole: "CODE_MAPPING",
        rendererKey: "ONE_PASS_LOOP",
        feedbackPolicy: { mode: "NONE" },
        data: {
          values: [6, 3, 5, 2],
          body: "比較する位置jを0、1、2と変化させるには、for文を使います。4つの値には隣り合う組が3組あるため、range(n - 1)でjを0から2まで動かします。",
          code: "for j in range(n - 1):\n    if numbers[j] > numbers[j + 1]:\n        numbers[j], numbers[j + 1] = numbers[j + 1], numbers[j]",
          emphasis: "j = 3まで進むとj + 1が位置4となり、配列の範囲外になります。そのためjは位置2までです。",
        },
      },
      preview: null,
      actionLabel: "次へ",
      order: 5,
    },
    {
      id: "algorithm-v2-bubble-sort-one-pass-build-v2",
      type: MissionActivityType.SELECT_FILL,
      title: "一周分のコードを完成させよう",
      instruction: "配列を左端から右端まで一周するように、コードブロックを正しい順番とインデントへ並べてください。",
      mentorMessage: "外側から「位置を動かす → 比べる → 入れ替える」の順番で組み立てよう！",
      content: {
        learningRole: "GUIDED_PRACTICE",
        rendererKey: "ONE_PASS_BUILD",
        feedbackPolicy: { mode: "RETRY_WITH_HINT", revealAfterAttempts: 2 },
        data: {
          values: [6, 3, 5, 2],
          codeBlockBuilder: true,
          builderInstruction: "ブロックをドラッグまたはクリックして、一周分のコードを組み立ててください",
          codePreviewPrefix: "numbers = [6, 3, 5, 2]\nn = len(numbers)",
          builderSlots: [
          { label: "比較位置を動かす", indent: 0 },
          { label: "交換が必要か判断", indent: 1 },
          { label: "値を交換", indent: 2 },
          ],
          codeBlocks: [
          { id: "loop-n-minus-one", label: "for j in range(n - 1):" },
          { id: "condition-j-greater", label: "if numbers[j] > numbers[j + 1]:" },
          { id: "swap-j-values", label: "numbers[j], numbers[j + 1] = numbers[j + 1], numbers[j]" },
          { id: "loop-n", label: "for j in range(n):", feedback: "jが最後の位置まで進むと、j + 1が配列の外にはみ出してしまうよ。隣り合う組の数を考えてみよう。" },
          { id: "condition-j-less", label: "if numbers[j] < numbers[j + 1]:", feedback: "昇順では、左の値が右の値より大きいときに交換するよ。" },
          { id: "keep-j-values", label: "numbers[j], numbers[j + 1] = numbers[j], numbers[j + 1]", feedback: "この代入では値の位置が変わらないよ。右辺の順番を反対にしよう。" },
          ],
          correctAnswers: ["loop-n-minus-one", "condition-j-greater", "swap-j-values"],
          executionResult: "[3, 5, 2, 6]",
          previewWaitingMessage: "3つのブロックを並べると、ここで一周後の配列を確認できます。",
          correctFeedback: "正解です。比較位置を右へ動かしながら、必要な場合だけ交換する一周分のコードを作れました。",
          incorrectFeedback: "比較と交換は、それぞれのjについて実行します。for文の内側へ、判断、交換の順に置いてみよう。",
          completionLabel: "次へ",
        },
      },
      preview: null,
      actionLabel: "コードを実行する",
      order: 6,
    },
    {
      id: "algorithm-v2-bubble-sort-one-pass-result-v2",
      type: MissionActivityType.CHOICE,
      title: "一周後の配列を確認しよう",
      instruction: "一周分の比較と交換が終わった後、配列がどのようになるか選んでください。",
      mentorMessage: "左から順番に追いかけて、一番大きい数字がどこへ移動するか見てみよう！",
      content: {
        learningRole: "INDEPENDENT_PRACTICE",
        rendererKey: "ONE_PASS_RESULT",
        feedbackPolicy: { mode: "RETRY_WITH_HINT", revealAfterAttempts: 2 },
        data: {
          values: [6, 3, 5, 2],
          code: "for j in range(n - 1):\n    if numbers[j] > numbers[j + 1]:\n        numbers[j], numbers[j + 1] = numbers[j + 1], numbers[j]",
          question: "一周分の処理が終わった後の配列を選んでください。",
          choices: [
          { id: "result-one-pass", label: "[3, 5, 2, 6]", isCorrect: true, feedback: "Mission 3クリア！ jを使って比較位置を右へ動かし、一周後に最も大きい6が右端へ移動することを確認できました。ただし5と2はまだ逆なので、次のMissionでは一周分の処理を複数回繰り返します。" },
          { id: "result-sorted", label: "[2, 3, 5, 6]", isCorrect: false, feedback: "これは全体を並べ替え終えた結果だよ。今回は一周だけ、6が右へ移動する流れを追ってみよう。" },
          { id: "result-middle", label: "[3, 6, 2, 5]", isCorrect: false, feedback: "6は隣の値より大きいたびに交換されるよ。右端まで追ってみよう。" },
          { id: "result-same", label: "[6, 3, 5, 2]", isCorrect: false, feedback: "6と3、6と5、6と2では交換が起きるよ。各比較後の配列を書き出してみよう。" },
          ],
          resultSteps: [[6, 3, 5, 2], [3, 6, 5, 2], [3, 5, 6, 2], [3, 5, 2, 6]],
          completionLabel: "Missionを完了",
        },
      },
      preview: null,
      actionLabel: "答えを確認する",
      order: 7,
    },
  ],
};

const missionFour: MissionSeed = {
  id: "algorithm-v2-bubble-sort-multiple-passes",
  title: "一周分の処理を繰り返そう",
  description: "一周だけでは残る未整列部分へ同じ処理を繰り返し、外側のfor文で配列全体を昇順へ並べます。",
  difficulty: CourseDifficulty.EASY,
  goalImg: "/images/missions/web-flow.png",
  estimatedMinutes: 16,
  order: 4,
  type: MissionType.MAIN,
  isRequiredForCourseCompletion: true,
  parentMissionId: null,
  roadmapLane: 0,
  branchOrder: 0,
  rewardExp: 160,
  learnedItems: ["一周だけでは全体が整わない", "一周分の処理を繰り返す", "周回をiで表す", "外側と内側の二重ループ", "n個の要素では最大n - 1周する", "複数周で配列全体を昇順にする"],
  isPublished: true,
  activities: [
    {
      id: "algorithm-v2-bubble-sort-multiple-passes-incomplete-v2",
      type: MissionActivityType.VIEW,
      title: "一周だけでは並べ替えが終わらない",
      instruction: "一周分の処理が終わった配列を見て、まだ並べ替えが必要な部分を確認しましょう。",
      mentorMessage: "一番大きい値は右端まで動いたけど、これで全部完成かな？",
      content: {
        learningRole: "EXPLANATION",
        rendererKey: "ONE_PASS_INCOMPLETE",
        feedbackPolicy: { mode: "NONE" },
        data: {
          beforeValues: [5, 2, 4, 1],
          afterValues: [2, 4, 1, 5],
          unsortedIndices: [1, 2],
          confirmedIndices: [3],
          body: "一周分の比較と交換によって、最も大きい5が右端へ移動しました。しかし、配列全体を見ると、4と1はまだ昇順になっていません。",
          emphasis: "一周だけでは、配列全体の並べ替えは終わりません。残っている値にも同じ処理を行います。",
        },
      },
      preview: null,
      actionLabel: "次へ",
      order: 1,
    },
    {
      id: "algorithm-v2-bubble-sort-multiple-passes-second-pass-v2",
      type: MissionActivityType.SELECT_FILL,
      title: "二周目の処理を進めよう",
      instruction: "一周後の配列に、もう一度左端から比較と交換を行いましょう。",
      mentorMessage: "やることは一周目と同じ！左から順番に比べていこう！",
      content: {
        learningRole: "GUIDED_PRACTICE",
        rendererKey: "SECOND_PASS_SEQUENCE",
        feedbackPolicy: { mode: "RETRY_WITH_HINT", revealAfterAttempts: 2 },
        data: {
          comparisonSequence: true,
          values: [2, 4, 1, 5],
          sequenceStates: [[2, 4, 1, 5], [2, 4, 1, 5], [2, 1, 4, 5]],
          finalValues: [2, 1, 4, 5],
          sequenceQuestions: [
          {
          currentPair: [0, 1],
          question: "2と4は交換しますか？",
          options: [{ id: "swap", label: "交換する" }, { id: "keep", label: "交換しない" }],
          afterMessage: "2は4より小さいので、すでに昇順です。交換しません。",
          },
          {
          currentPair: [1, 2],
          question: "4と1は交換しますか？",
          options: [{ id: "swap", label: "交換する" }, { id: "keep", label: "交換しない" }],
          afterMessage: "4は1より大きいので、2つの値を交換します。",
          },
          {
          currentPair: [2, 3],
          question: "4と5は交換しますか？",
          options: [{ id: "swap", label: "交換する" }, { id: "keep", label: "交換しない" }],
          afterMessage: "4は5より小さいので、交換する必要はありません。",
          },
          ],
          correctAnswers: ["keep", "swap", "keep"],
          correctFeedback: "正解です。二周目が終わり、配列は[2, 1, 4, 5]になりました。一周目より昇順に近づきましたが、2と1はまだ逆です。",
          incorrectFeedback: "昇順では、左の値が右の値より大きいときだけ交換するよ。各ステップをもう一度確認しよう。",
          completionLabel: "次へ",
        },
      },
      preview: null,
      actionLabel: "答えを確認する",
      order: 2,
    },
    {
      id: "algorithm-v2-bubble-sort-multiple-passes-overview-v2",
      type: MissionActivityType.VIEW,
      title: "複数周で配列が整う様子を見よう",
      instruction: "一周分の処理を繰り返したとき、配列がどのように変化するか確認しましょう。",
      mentorMessage: "一周するたびに、大きい値が右側へ集まっていくよ！",
      content: {
        learningRole: "EXPLANATION",
        rendererKey: "ARRAY_TRACE",
        feedbackPolicy: { mode: "NONE" },
        data: {
          values: [5, 2, 4, 1],
          steps: [
          { values: [5, 2, 4, 1], message: "開始前：まだ並べ替えは始まっていません。" },
          { values: [2, 4, 1, 5], message: "一周目の後：最も大きい5が右端へ移動しました。", confirmedIndices: [3], pointers: [{ index: 3, label: "確定", tone: "success" }] },
          { values: [2, 1, 4, 5], message: "二周目の後：次に大きい4が右側へ移動しました。", confirmedIndices: [2, 3], pointers: [{ index: 2, label: "確定", tone: "success" }] },
          { values: [1, 2, 4, 5], message: "三周目の後：2と1が正しい順番になり、昇順が完成しました。", confirmedIndices: [0, 1, 2, 3] },
          ],
          finalMessage: "一周分の処理を繰り返すことで、配列全体を少しずつ昇順へ近づけられます。4つの値では最大3周します。",
          intervalMs: 1200,
        },
      },
      preview: null,
      actionLabel: "次へ",
      order: 3,
    },
    {
      id: "algorithm-v2-bubble-sort-multiple-passes-i-loop-v2",
      type: MissionActivityType.VIEW,
      title: "周回をiで表そう",
      instruction: "一周分の処理を繰り返すために、周回を変数iで表す方法を確認しましょう。",
      mentorMessage: "比較する位置はj、何周目かはiに任せよう！",
      content: {
        learningRole: "CODE_MAPPING",
        rendererKey: "I_LOOP_MAPPING",
        feedbackPolicy: { mode: "NONE" },
        data: {
          values: [5, 2, 4, 1],
          body: "一周分の処理を何回繰り返したかをiで表します。4要素ではrange(n - 1)がrange(3)となり、iには0、1、2が入ります。",
          loopCode: "for i in range(n - 1):",
          passMappings: [{ label: "一周目", i: 0 }, { label: "二周目", i: 1 }, { label: "三周目", i: 2 }],
          emphasis: "iは何周目の処理かを表し、jはその周回内で比較する位置を表します。要素数がnなら最大n - 1周します。",
        },
      },
      preview: null,
      actionLabel: "次へ",
      order: 4,
    },
    {
      id: "algorithm-v2-bubble-sort-multiple-passes-nested-loop-v2",
      type: MissionActivityType.VIEW,
      title: "一周分の処理を繰り返すコードを見よう",
      instruction: "一周分の処理を複数回繰り返すコードの構造を確認しましょう。",
      mentorMessage: "外側のループが周回、内側のループが一周分の移動だよ！",
      content: {
        learningRole: "CODE_MAPPING",
        rendererKey: "NESTED_LOOP_STRUCTURE",
        feedbackPolicy: { mode: "NONE" },
        data: {
          values: [5, 2, 4, 1],
          code: "numbers = [5, 2, 4, 1]\nn = len(numbers)\n\nfor i in range(n - 1):\n    for j in range(n - 1):\n        if numbers[j] > numbers[j + 1]:\n            numbers[j], numbers[j + 1] = numbers[j + 1], numbers[j]",
          codeRoles: [
          { id: "outer-loop", label: "外側のfor文", code: "for i in range(n - 1):", role: "一周分の処理全体を繰り返す", tone: "blue" },
          { id: "inner-loop", label: "内側のfor文", code: "for j in range(n - 1):", role: "その周回で比較位置を左から右へ動かす", tone: "green" },
          { id: "condition", label: "比較条件", code: "if numbers[j] > numbers[j + 1]:", role: "左の値が右の値より大きいか確認する", tone: "amber" },
          { id: "swap", label: "交換処理", code: "numbers[j], numbers[j + 1] = numbers[j + 1], numbers[j]", role: "条件が成り立ったときに隣り合う値を交換する", tone: "purple" },
          ],
          loopMappings: [{ i: 0, js: [0, 1, 2] }, { i: 1, js: [0, 1, 2] }, { i: 2, js: [0, 1, 2] }],
          warning: "現在のコードでは、どの周回でも左端から右端まで同じ回数だけ比較します。正しく整列しますが、右側へ移動済みの値も再比較します。比較範囲の短縮は次のMissionで学びます。",
        },
      },
      preview: null,
      actionLabel: "次へ",
      order: 5,
    },
    {
      id: "algorithm-v2-bubble-sort-multiple-passes-build-v2",
      type: MissionActivityType.SELECT_FILL,
      title: "複数周のコードを完成させよう",
      instruction: "一周分の処理を複数回繰り返すように、コードブロックを正しい順番と階層へ並べてください。",
      mentorMessage: "まず周回を作って、その中に一周分の処理を丸ごと入れよう！",
      content: {
        learningRole: "GUIDED_PRACTICE",
        rendererKey: "MULTI_PASS_BUILD",
        feedbackPolicy: { mode: "RETRY_WITH_HINT", revealAfterAttempts: 2 },
        data: {
          values: [5, 2, 4, 1],
          codeBlockBuilder: true,
          builderInstruction: "ブロックをドラッグまたはクリックして、複数周のコードを組み立ててください",
          codePreviewPrefix: "numbers = [5, 2, 4, 1]\nn = len(numbers)",
          builderSlots: [
          { label: "周回を繰り返す", indent: 0 },
          { label: "比較位置を動かす", indent: 1 },
          { label: "交換条件", indent: 2 },
          { label: "交換処理", indent: 3 },
          ],
          codeBlocks: [
          { id: "outer-loop-n-minus-one", label: "for i in range(n - 1):" },
          { id: "inner-loop-n-minus-one", label: "for j in range(n - 1):" },
          { id: "condition-j-greater-m4", label: "if numbers[j] > numbers[j + 1]:" },
          { id: "swap-j-values-m4", label: "numbers[j], numbers[j + 1] = numbers[j + 1], numbers[j]" },
          { id: "outer-loop-n", label: "for i in range(n):", feedback: "最大周回数はn - 1回です。要素数4ならiは0、1、2と動きます。" },
          { id: "inner-loop-n", label: "for j in range(n):", feedback: "j + 1が配列の外へ出ないように、比較できる組の数を考えよう。" },
          { id: "condition-j-less-m4", label: "if numbers[j] < numbers[j + 1]:", feedback: "昇順では、左の値が右の値より大きいときに交換するよ。" },
          { id: "keep-j-values-m4", label: "numbers[j], numbers[j + 1] = numbers[j], numbers[j + 1]", feedback: "この代入では値の位置が変わらないよ。右辺の順番を反対にしよう。" },
          ],
          correctAnswers: ["outer-loop-n-minus-one", "inner-loop-n-minus-one", "condition-j-greater-m4", "swap-j-values-m4"],
          executionResult: "[1, 2, 4, 5]",
          previewWaitingMessage: "4つのブロックを並べると、ここで複数周後の配列を確認できます。",
          correctFeedback: "正解です。外側のfor文で一周分の処理を繰り返し、内側のfor文で隣り合う値を順番に比較できました。",
          incorrectFeedback: "何周も繰り返す処理の中に、一周分の比較・条件・交換を順番に入れよう。コードの階層も確認してみよう。",
          completionLabel: "次へ",
        },
      },
      preview: null,
      actionLabel: "コードを実行する",
      order: 6,
    },
    {
      id: "algorithm-v2-bubble-sort-multiple-passes-result-v2",
      type: MissionActivityType.CHOICE,
      title: "複数周後の配列を確認しよう",
      instruction: "一周分の処理を繰り返した後、配列がどのようになるか選んでください。",
      mentorMessage: "今度は一周だけじゃないよ。最後まで追いかけてみよう！",
      content: {
        learningRole: "INDEPENDENT_PRACTICE",
        rendererKey: "MULTI_PASS_RESULT",
        feedbackPolicy: { mode: "RETRY_WITH_HINT", revealAfterAttempts: 2 },
        data: {
          values: [6, 3, 5, 2],
          code: "n = len(numbers)\n\nfor i in range(n - 1):\n    for j in range(n - 1):\n        if numbers[j] > numbers[j + 1]:\n            numbers[j], numbers[j + 1] = numbers[j + 1], numbers[j]",
          question: "すべての周回が終わった後の配列を選んでください。",
          choices: [
          { id: "result-first-pass", label: "[3, 5, 2, 6]", isCorrect: false, feedback: "これは一周目の結果だよ。この結果へ同じ一周分の処理をさらに適用してみよう。" },
          { id: "result-all-passes", label: "[2, 3, 5, 6]", isCorrect: true, feedback: "Mission 4クリア！ 外側のfor文で一周分の処理を繰り返し、配列全体を昇順に並べられました。次のMissionでは、周回ごとに比較範囲を短くして不要な比較を減らします。" },
          { id: "result-second-pass", label: "[3, 2, 5, 6]", isCorrect: false, feedback: "これは二周目の結果だよ。残る3と2にも、もう一周同じ処理を適用しよう。" },
          { id: "result-initial", label: "[6, 3, 5, 2]", isCorrect: false, feedback: "比較と交換を繰り返すと配列は変化するよ。大きい値が右へ移動する様子を追ってみよう。" },
          ],
          passStates: [
          { label: "開始前", values: [6, 3, 5, 2] },
          { label: "一周目", values: [3, 5, 2, 6] },
          { label: "二周目", values: [3, 2, 5, 6] },
          { label: "三周目", values: [2, 3, 5, 6] },
          ],
          completionLabel: "Missionを完了",
        },
      },
      preview: null,
      actionLabel: "答えを確認する",
      order: 7,
    },
  ],
};

const missionFive: MissionSeed = {
  id: "algorithm-v2-bubble-sort-range",
  title: "比較範囲を短くしよう",
  description: "位置が決まった右側の値を比較範囲から除き、周回数iを使って不要な比較を減らします。",
  difficulty: CourseDifficulty.EASY,
  goalImg: "/images/missions/web-flow.png",
  estimatedMinutes: 14,
  order: 5,
  type: MissionType.MAIN,
  isRequiredForCourseCompletion: true,
  parentMissionId: null,
  roadmapLane: 0,
  branchOrder: 0,
  rewardExp: 140,
  learnedItems: [
    "一周ごとに右側の値の位置が決まる",
    "確定済みの値は再比較しなくてよい",
    "周回数iと比較範囲の関係",
    "比較範囲をn - 1 - iで表す",
    "整列結果を変えずに比較回数を減らす",
  ],
  isPublished: true,
  activities: [
    {
      id: "algorithm-v2-bubble-sort-range-redundancy-v2",
      type: MissionActivityType.VIEW,
      title: "同じ範囲を毎回比較する必要はある？",
      instruction: "周回ごとの比較位置を見て、不要になっている比較がないか確認しましょう。",
      mentorMessage: "もう正しい位置にいる数字まで、また比べていないかな？",
      content: {
        learningRole: "EXPLANATION",
        rendererKey: "RANGE_REDUNDANCY",
        feedbackPolicy: { mode: "NONE" },
        data: {
          initialValues: [5, 2, 4, 1],
          afterFirstPass: [2, 4, 1, 5],
          confirmedIndices: [3],
          comparisonPairs: [[0, 1], [1, 2], [2, 3]],
          body: "一周目によって、最も大きい5が右端へ移動しました。二周目でも同じ範囲を使うと、最後に1と5をもう一度比較してしまいます。",
          emphasis: "一周終わるたびに、右側から1つずつ値の位置が決まります。周回が進むほど、比較する範囲を短くできます。",
        },
      },
      preview: null,
      actionLabel: "次へ",
      order: 1,
    },
    {
      id: "algorithm-v2-bubble-sort-range-next-range-v2",
      type: MissionActivityType.CHOICE,
      title: "次の周回で比較する範囲を選ぼう",
      instruction: "一周目が終わった配列を見て、二周目で比較する範囲を選んでください。",
      mentorMessage: "右端の数字はもうお休み！残った範囲だけ見てみよう！",
      content: {
        learningRole: "GUIDED_PRACTICE",
        rendererKey: "NEXT_ACTIVE_RANGE",
        feedbackPolicy: { mode: "RETRY_WITH_HINT", revealAfterAttempts: 2 },
        data: {
          values: [2, 4, 1, 5],
          confirmedIndices: [3],
          activeRange: [0, 2],
          comparisonPairs: [[0, 1], [1, 2]],
          body: "右端の5は一周目で位置が決まっています。残った範囲で、二周目の最後に比較する組を考えましょう。",
          question: "二周目では、どこまで比較すればよいですか？",
          choices: [
          { id: "range-through-0-1", label: "位置0と位置1まで", isCorrect: false, feedback: "まだ位置1と位置2の順番も確認する必要があるよ。右端の5だけを除いて考えよう。" },
          { id: "range-through-1-2", label: "位置1と位置2まで", isCorrect: true, feedback: "正解です。二周目では位置0と1、位置1と2の2組を比較します。右端の5は比較しません。" },
          { id: "range-through-2-3", label: "位置2と位置3まで", isCorrect: false, feedback: "位置3の5は一周目で右端へ移動し、位置が決まっているよ。次の周回では除けます。" },
          { id: "range-none", label: "比較する必要はない", isCorrect: false, feedback: "2、4、1はまだ昇順ではないよ。確定した右端以外には、もう一周必要です。" },
          ],
          correctRangeMessage: "二周目では、位置0と位置1、位置1と位置2の2組を比較します。",
          completionLabel: "次へ",
        },
      },
      preview: null,
      actionLabel: "答えを確認する",
      order: 2,
    },
    {
      id: "algorithm-v2-bubble-sort-range-by-pass-v2",
      type: MissionActivityType.VIEW,
      title: "周回ごとの比較範囲を見よう",
      instruction: "一周目、二周目、三周目で、比較する範囲がどのように変わるか確認しましょう。",
      mentorMessage: "右側が完成するたびに、見る範囲も少しずつ短くなるよ！",
      content: {
        learningRole: "EXPLANATION",
        rendererKey: "RANGE_BY_PASS",
        feedbackPolicy: { mode: "NONE" },
        data: {
          body: "一周ごとに右側の位置が決まり、次の周回で比較する隣接ペアが1組ずつ減ります。",
          passRanges: [
          { label: "一周目", i: 0, values: [5, 2, 4, 1], pairs: [[0, 1], [1, 2], [2, 3]], comparisonCount: 3, result: [2, 4, 1, 5], confirmedIndices: [3] },
          { label: "二周目", i: 1, values: [2, 4, 1, 5], pairs: [[0, 1], [1, 2]], comparisonCount: 2, result: [2, 1, 4, 5], confirmedIndices: [2, 3] },
          { label: "三周目", i: 2, values: [2, 1, 4, 5], pairs: [[0, 1]], comparisonCount: 1, result: [1, 2, 4, 5], confirmedIndices: [0, 1, 2, 3] },
          ],
          emphasis: "周回が1つ進むたびに、比較回数も1回ずつ減ります。",
        },
      },
      preview: null,
      actionLabel: "次へ",
      order: 3,
    },
    {
      id: "algorithm-v2-bubble-sort-range-formula-v2",
      type: MissionActivityType.VIEW,
      title: "比較回数を式で表そう",
      instruction: "配列の長さと周回数を使って、必要な比較回数を式で表しましょう。",
      mentorMessage: "最初はn - 1回。そこから終わった周回分を引けばよさそうだね！",
      content: {
        learningRole: "CODE_MAPPING",
        rendererKey: "RANGE_FORMULA",
        feedbackPolicy: { mode: "NONE" },
        data: {
          body: "最初の周回はn - 1回比較します。一周終わるたびに、右側から1つずつ比較しなくてよい値が増えます。",
          formula: "n - 1 - i",
          rows: [
          { label: "一周目", i: 0, expression: "4 - 1 - 0", result: 3 },
          { label: "二周目", i: 1, expression: "4 - 1 - 1", result: 2 },
          { label: "三周目", i: 2, expression: "4 - 1 - 2", result: 1 },
          ],
          emphasis: "iが増えるほど、n - 1 - iは小さくなります。iは何周終わったかを表すため、その分だけ右側を省けます。",
        },
      },
      preview: null,
      actionLabel: "次へ",
      order: 4,
    },
    {
      id: "algorithm-v2-bubble-sort-range-fill-v2",
      type: MissionActivityType.SELECT_FILL,
      title: "比較範囲の式を完成させよう",
      instruction: "周回が進むたびに比較回数が1回ずつ減るように、空欄へ入る式を選んでください。",
      mentorMessage: "n - 1から、終わった周回の数を引いてみよう！",
      content: {
        learningRole: "CODE_MAPPING",
        rendererKey: "RANGE_FILL",
        feedbackPolicy: { mode: "RETRY_WITH_HINT", revealAfterAttempts: 2 },
        data: {
          optionFill: true,
          body: "内側のfor文の空欄を完成させ、確定済みの右側を次の周回から除外しましょう。",
          code: "for i in range(n - 1):\n    for j in range(＿＿＿＿＿＿):\n        if numbers[j] > numbers[j + 1]:\n            numbers[j], numbers[j + 1] = numbers[j + 1], numbers[j]",
          completedCode: "for i in range(n - 1):\n    for j in range(n - 1 - i):\n        if numbers[j] > numbers[j + 1]:\n            numbers[j], numbers[j + 1] = numbers[j + 1], numbers[j]",
          fillOptions: [
          { id: "n", label: "n" },
          { id: "n-minus-one", label: "n - 1" },
          { id: "n-minus-i", label: "n - i" },
          { id: "n-minus-one-minus-i", label: "n - 1 - i" },
          ],
          correctAnswers: "n-minus-one-minus-i",
          optionFeedback: {
          n: "j + 1が配列の範囲外になる可能性があるよ。隣り合う組の数は要素数より1つ少なくなります。",
          "n-minus-one": "並べ替えはできますが、毎周同じ回数だけ比較します。周回数iを使ってみよう。",
          "n-minus-i": "一周目ではn回になり、比較回数が1回多くなります。最初はn - 1回です。",
          },
          correctFeedback: "正解です。最初はi = 0なのでn - 1回比較し、周回が進むたびに比較範囲が1つずつ短くなります。",
          incorrectFeedback: "最初の比較回数n - 1から、終わった周回の数iを引いてみよう。",
          completionLabel: "次へ",
        },
      },
      preview: null,
      actionLabel: "答えを確認する",
      order: 5,
    },
    {
      id: "algorithm-v2-bubble-sort-range-playback-v2",
      type: MissionActivityType.VIEW,
      title: "最適化したコードの動きを確認しよう",
      instruction: "コードを実行し、周回ごとに比較する範囲がどのように変わるか観察しましょう。",
      mentorMessage: "同じ結果になるけど、今度はムダな比較が減っているよ！",
      content: {
        learningRole: "EXPLANATION",
        rendererKey: "ARRAY_TRACE",
        feedbackPolicy: { mode: "NONE" },
        data: {
          values: [5, 2, 4, 1],
          code: "numbers = [5, 2, 4, 1]\nn = len(numbers)\n\nfor i in range(n - 1):\n    for j in range(n - 1 - i):\n        if numbers[j] > numbers[j + 1]:\n            numbers[j], numbers[j + 1] = numbers[j + 1], numbers[j]",
          steps: [
            { values: [5, 2, 4, 1], message: "一周目は配列全体の3組を比較します。", pointers: [{ index: 3, label: "比較の終点", tone: "primary" }], activeCodeLines: [4, 5] },
            { values: [2, 4, 1, 5], message: "一周目が終了し、右端の5が確定しました。", confirmedIndices: [3], activeCodeLines: [4] },
            { values: [2, 4, 1, 5], message: "二周目は確定した右端を除き、2組だけ比較します。", confirmedIndices: [3], excludedIndices: [3], pointers: [{ index: 2, label: "比較の終点", tone: "primary" }], activeCodeLines: [4, 5] },
            { values: [2, 1, 4, 5], message: "二周目が終了し、右側の4と5が確定しました。", confirmedIndices: [2, 3], activeCodeLines: [4] },
            { values: [2, 1, 4, 5], message: "三周目は左端の1組だけを比較します。", confirmedIndices: [2, 3], excludedIndices: [2, 3], pointers: [{ index: 1, label: "比較の終点", tone: "primary" }], activeCodeLines: [4, 5] },
            { values: [1, 2, 4, 5], message: "3回、2回、1回と範囲を短くしながら、6回の比較で昇順になりました。", confirmedIndices: [0, 1, 2, 3], activeCodeLines: [] },
          ],
          body: "range(n - 1 - i)を使うと、一周目は3回、二周目は2回、三周目は1回だけ比較します。",
          finalMessage: "並べ替え結果は同じですが、毎周3回比較するコードより不要な比較を3回減らせました。",
          intervalMs: 1100,
        },
      },
      preview: null,
      actionLabel: "次へ",
      order: 6,
    },
    {
      id: "algorithm-v2-bubble-sort-range-compare-v2",
      type: MissionActivityType.CHOICE,
      title: "最適化前後を比べよう",
      instruction: "2つのコードを見比べ、正しい説明を選んでください。",
      mentorMessage: "答えが同じでも、途中のムダを減らせるかがポイントだよ！",
      content: {
        learningRole: "INDEPENDENT_PRACTICE",
        rendererKey: "OPTIMIZATION_COMPARE",
        feedbackPolicy: { mode: "RETRY_WITH_HINT", revealAfterAttempts: 2 },
        data: {
          values: [5, 2, 4, 1],
          codeA: "for i in range(n - 1):\n    for j in range(n - 1):\n        if numbers[j] > numbers[j + 1]:\n            numbers[j], numbers[j + 1] = numbers[j + 1], numbers[j]",
          codeB: "for i in range(n - 1):\n    for j in range(n - 1 - i):\n        if numbers[j] > numbers[j + 1]:\n            numbers[j], numbers[j + 1] = numbers[j + 1], numbers[j]",
          body: "コードAは毎周同じ範囲を比較し、コードBは周回ごとに確定済みの右側を除外します。",
          question: "コードAとコードBについて、正しい説明を選んでください。",
          choices: [
          { id: "only-a-correct", label: "コードAだけが正しく昇順へ並べ替えられる", isCorrect: false, feedback: "コードBも未確定範囲はすべて比較するため、正しく昇順になります。" },
          { id: "only-b-correct", label: "コードBだけが正しく昇順へ並べ替えられる", isCorrect: false, feedback: "コードAも比較が多いだけで、配列は正しく昇順になります。" },
          { id: "same-result-fewer", label: "どちらも同じ結果になるが、コードBの方が比較回数を減らせる", isCorrect: true, feedback: "Mission 5クリア！ どちらも[1, 2, 4, 5]になりますが、コードBは比較を9回から6回へ減らせます。次はバブルソート全体のコードを完成させます。" },
          { id: "same-count", label: "どちらも比較回数は同じになる", isCorrect: false, feedback: "各周回でjが何回動くか比べよう。コードBは3回、2回、1回と短くなります。" },
          ],
          resultA: [1, 2, 4, 5],
          resultB: [1, 2, 4, 5],
          comparisonCountA: 9,
          comparisonCountB: 6,
          completionLabel: "Missionを完了",
        },
      },
      preview: null,
      actionLabel: "答えを確認する",
      order: 7,
    },
  ],
};

const missionSix: MissionSeed = {
  id: "algorithm-v2-bubble-sort-python",
  title: "バブルソートのコードを完成させよう",
  description: "これまで学んだ比較・交換・一周分の繰り返し・複数周・比較範囲の調整を整理し、すべてを組み合わせてバブルソートの完成コードを作ります。",
  difficulty: CourseDifficulty.EASY,
  goalImg: "/images/missions/web-flow.png",
  estimatedMinutes: 19,
  order: 6,
  type: MissionType.MAIN,
  isRequiredForCourseCompletion: true,
  parentMissionId: null,
  roadmapLane: 0,
  branchOrder: 0,
  rewardExp: 190,
  learnedItems: [
    "バブルソートを構成する処理の全体像",
    "iとjの役割",
    "比較条件と交換処理の関係",
    "不完全なコードの修正",
    "完成コードの説明",
  ],
  isPublished: true,
  activities: [
    {
      id: "algorithm-v2-bubble-sort-python-review-v2",
      type: MissionActivityType.VIEW,
      title: "完成までの処理を振り返ろう",
      instruction: "バブルソートを構成する4つの処理と、それぞれの役割を確認しましょう。",
      mentorMessage: "今まで覚えたパーツを、ここでいったん全部並べてみよう！",
      content: {
        learningRole: "SYNTHESIS",
        rendererKey: "COMPLETE_PROCESS_REVIEW",
        feedbackPolicy: { mode: "NONE" },
        data: {
          processes: [
          { code: "for i in range(n - 1):", role: "一周分の処理を最大でn - 1回繰り返す" },
          { code: "for j in range(n - 1 - i):", role: "周回の中で比較する位置を左から右へ動かす" },
          { code: "if numbers[j] > numbers[j + 1]:", role: "左の値が右の値より大きいか確認する" },
          { code: "numbers[j], numbers[j + 1] = numbers[j + 1], numbers[j]", role: "条件が成立したとき隣り合う値を交換する" },
          ],
          flow: ["周回を始める", "比較位置を動かす", "隣り合う値を比較する", "必要なら交換する", "次の比較位置へ進む", "次の周回へ進む"],
          emphasis: "バブルソートは、これまで学んだ4つの処理を組み合わせて作られています。",
        },
      },
      preview: null,
      actionLabel: "次へ",
      order: 1,
    },
    {
      id: "algorithm-v2-bubble-sort-python-loop-roles-v2",
      type: MissionActivityType.SELECT_FILL,
      title: "iとjの役割を整理しよう",
      instruction: "iとjが、それぞれ何を表しているか選んでください。",
      mentorMessage: "iとjは似て見えるけど、担当している仕事は別々だよ！",
      content: {
        learningRole: "SYNTHESIS",
        rendererKey: "LOOP_ROLE_REVIEW",
        feedbackPolicy: { mode: "RETRY_WITH_HINT", revealAfterAttempts: 2 },
        data: {
          code: "for i in range(n - 1):\n    for j in range(n - 1 - i):\n        if numbers[j] > numbers[j + 1]:\n            numbers[j], numbers[j + 1] = numbers[j + 1], numbers[j]",
          multiDecision: true,
          decisionPairs: [{ id: "i-role" }, { id: "j-role" }],
          roleQuestions: [
          {
          id: "i-role",
          variable: "i",
          question: "iは何を表していますか？",
          options: [
          { id: "left-value", label: "比較する左側の値" },
          { id: "pass-number", label: "何周目の処理か" },
          { id: "length", label: "配列の要素数" },
          { id: "swap-count", label: "交換した回数" },
          ],
          explanation: "iは、一周分の処理を何回実行したかを表します。",
          },
          {
          id: "j-role",
          variable: "j",
          question: "jは何を表していますか？",
          options: [
          { id: "pass-number", label: "何周目の処理か" },
          { id: "maximum", label: "配列の最大値" },
          { id: "compare-position", label: "その周回で比較する位置" },
          { id: "mission-count", label: "完了したMissionの数" },
          ],
          explanation: "jは、その周回の中で比較する左側の位置を表します。",
          },
          ],
          correctAnswers: { "i-role": "pass-number", "j-role": "compare-position" },
          correctFeedback: "iは何周目か、jはその周回で比較する位置を表します。2つの役割を区別できました。",
          incorrectFeedback: "外側のループと内側のループが、それぞれ何を繰り返しているか見てみよう。",
          completionLabel: "次へ",
        },
      },
      preview: null,
      actionLabel: "答えを確認する",
      order: 2,
    },
    {
      id: "algorithm-v2-bubble-sort-python-order-v2",
      type: MissionActivityType.ORDERED_STEPS,
      title: "コードを実行する順番を確認しよう",
      instruction: "バブルソートの処理が実行される順番に、説明カードを並べてください。",
      mentorMessage: "コードを上から追いかけて、どの処理が先に動くか考えてみよう！",
      content: {
        learningRole: "SYNTHESIS",
        rendererKey: "EXECUTION_ORDER",
        feedbackPolicy: { mode: "RETRY_WITH_HINT", revealAfterAttempts: 2 },
        data: {
          code: "numbers = [5, 2, 4, 1]\nn = len(numbers)\n\nfor i in range(n - 1):\n    for j in range(n - 1 - i):\n        if numbers[j] > numbers[j + 1]:\n            numbers[j], numbers[j + 1] = numbers[j + 1], numbers[j]",
          steps: [
          { id: "swap", label: "必要な場合に2つの値を交換する" },
          { id: "start-pass", label: "一周目を開始する" },
          { id: "compare", label: "左の値が右の値より大きいか確認する" },
          { id: "move-j", label: "比較する位置を1つ右へ動かす" },
          { id: "next-pass", label: "一周が終わったら次の周回へ進む" },
          ],
          answerOrder: ["start-pass", "compare", "swap", "move-j", "next-pass"],
          correctFeedback: "周回の中で比較と交換を右へ進め、一周が終わると次の周回へ移ります。",
          incorrectFeedback: "まず外側のfor文で周回を始め、その中でjを動かします。ユーザーの並び順は保持されています。",
          completionLabel: "次へ",
        },
      },
      preview: null,
      actionLabel: "答えを確認する",
      order: 3,
    },
    {
      id: "algorithm-v2-bubble-sort-python-missing-v2",
      type: MissionActivityType.CHOICE,
      title: "不足している処理を見つけよう",
      instruction: "コードに不足している、バブルソートに必要な処理を選んでください。",
      mentorMessage: "動かす、比べる、入れ替える……どの部分が抜けているかな？",
      content: {
        learningRole: "SYNTHESIS",
        rendererKey: "MISSING_CONDITION",
        feedbackPolicy: { mode: "RETRY_WITH_HINT", revealAfterAttempts: 2 },
        data: {
          code: "numbers = [5, 2, 4, 1]\nn = len(numbers)\n\nfor i in range(n - 1):\n    for j in range(n - 1 - i):\n        numbers[j], numbers[j + 1] = numbers[j + 1], numbers[j]",
          correctedCode: "numbers = [5, 2, 4, 1]\nn = len(numbers)\n\nfor i in range(n - 1):\n    for j in range(n - 1 - i):\n        if numbers[j] > numbers[j + 1]:\n            numbers[j], numbers[j + 1] = numbers[j + 1], numbers[j]",
          question: "このコードに不足している処理はどれですか？",
          choices: [
          { id: "length", label: "配列の長さを求める処理", isCorrect: false, feedback: "n = len(numbers)で、配列の長さはすでに求めています。" },
          { id: "outer-loop", label: "外側の繰り返し", isCorrect: false, feedback: "for i in range(n - 1)が外側の繰り返しです。" },
          { id: "condition", label: "交換が必要か判断する条件", isCorrect: true, feedback: "条件がないと、値の大小を確認せずにすべての隣接要素を交換してしまいます。昇順では左の値が大きい場合だけ交換します。" },
          { id: "move", label: "交換する位置を右へ動かす処理", isCorrect: false, feedback: "内側のfor文でjが増え、比較位置は右へ動いています。" },
          ],
          completionLabel: "次へ",
        },
      },
      preview: null,
      actionLabel: "答えを確認する",
      order: 4,
    },
    {
      id: "algorithm-v2-bubble-sort-python-repair-v2",
      type: MissionActivityType.SELECT_FILL,
      title: "間違っているコードを修正しよう",
      instruction: "コードにある2か所の誤りを見つけ、正しいコードへ修正してください。",
      mentorMessage: "昇順の条件と、比較する範囲に注目してみよう！",
      content: {
        learningRole: "SYNTHESIS",
        rendererKey: "CODE_REPAIR",
        feedbackPolicy: { mode: "RETRY_WITH_HINT", revealAfterAttempts: 2 },
        data: {
          code: "numbers = [5, 2, 4, 1]\nn = len(numbers)\n\nfor i in range(n - 1):\n    for j in range(n):\n        if numbers[j] < numbers[j + 1]:\n            numbers[j], numbers[j + 1] = numbers[j + 1], numbers[j]",
          correctedCode: "numbers = [5, 2, 4, 1]\nn = len(numbers)\n\nfor i in range(n - 1):\n    for j in range(n - 1 - i):\n        if numbers[j] > numbers[j + 1]:\n            numbers[j], numbers[j + 1] = numbers[j + 1], numbers[j]",
          multiDecision: true,
          decisionPairs: [{ id: "range" }, { id: "operator" }],
          repairQuestions: [
          { id: "range", label: "内側のrange", options: ["range(n)", "range(n - 1)", "range(n - 1 - i)", "range(i)"] },
          { id: "operator", label: "比較演算子", options: ["<", ">", "==", "!="] },
          ],
          correctAnswers: { range: "range(n - 1 - i)", operator: ">" },
          correctFeedback: "range(n - 1 - i)で比較範囲を調整し、>で昇順の交換条件を表せました。",
          incorrectFeedback: "range(n)ではj + 1が範囲外になります。<では大きい値が左へ移動するため、昇順の条件と範囲を両方見直そう。",
          completionLabel: "次へ",
        },
      },
      preview: null,
      actionLabel: "コードを修正する",
      order: 5,
    },
    {
      id: "algorithm-v2-bubble-sort-python-build-v2",
      type: MissionActivityType.SELECT_FILL,
      title: "バブルソート全体を完成させよう",
      instruction: "コードブロックを正しい順番とインデントへ並べ、バブルソート全体を完成させてください。",
      mentorMessage: "いよいよ全部合体！周回の中に、一周分の処理を組み立てよう！",
      content: {
        learningRole: "SYNTHESIS",
        rendererKey: "COMPLETE_CODE_BUILD",
        feedbackPolicy: { mode: "RETRY_WITH_HINT", revealAfterAttempts: 2 },
        data: {
          codeBlockBuilder: true,
          codePreviewPrefix: "numbers = [5, 2, 4, 1]\nn = len(numbers)",
          builderInstruction: "ブロックをドラッグまたはクリックし、外側から『周回 → 比較位置 → 条件 → 交換』の順に配置してください",
          builderSlots: [
          { label: "外側の繰り返し", indent: 0 },
          { label: "内側の繰り返し", indent: 1 },
          { label: "比較条件", indent: 2 },
          { label: "交換処理", indent: 3 },
          ],
          codeBlocks: [
          { id: "outer", label: "for i in range(n - 1):" },
          { id: "inner", label: "for j in range(n - 1 - i):" },
          { id: "condition", label: "if numbers[j] > numbers[j + 1]:" },
          { id: "swap", label: "numbers[j], numbers[j + 1] = numbers[j + 1], numbers[j]" },
          { id: "wrong-outer", label: "for i in range(n):", feedback: "外側の周回は最大n - 1回です。" },
          { id: "wrong-inner", label: "for j in range(n):", feedback: "j + 1が範囲外にならないようにし、確定済み範囲を除きます。" },
          { id: "wrong-condition", label: "if numbers[j] < numbers[j + 1]:", feedback: "昇順では左側が大きい場合に交換します。" },
          { id: "wrong-swap", label: "numbers[j], numbers[j + 1] = numbers[j], numbers[j + 1]", feedback: "右辺の順番を入れ替えないと値は交換されません。" },
          ],
          correctAnswers: ["outer", "inner", "condition", "swap"],
          executionResult: "[1, 2, 4, 5]",
          previewWaitingMessage: "4つのブロックを組み立てると、ここで実行結果を確認できます。",
          correctFeedback: "バブルソートの完成です！周回、比較位置、交換条件、交換処理を正しく組み合わせられました。",
          incorrectFeedback: "外側から『周回 → 比較位置 → 条件 → 交換』の順番で考えてみよう。",
          completionLabel: "次へ",
        },
      },
      preview: null,
      actionLabel: "コードを実行する",
      order: 6,
    },
    {
      id: "algorithm-v2-bubble-sort-python-explain-v2",
      type: MissionActivityType.MATCH,
      title: "完成コードの動きを説明しよう",
      instruction: "完成コードの各部分と、その役割を正しく組み合わせてください。",
      mentorMessage: "書けるだけじゃなく、コードの意味まで説明できたら完璧だよ！",
      content: {
        learningRole: "SYNTHESIS",
        rendererKey: "COMPLETE_CODE_MATCH",
        feedbackPolicy: { mode: "RETRY_WITH_HINT", revealAfterAttempts: 2 },
        data: {
          code: "numbers = [6, 3, 5, 2]\nn = len(numbers)\n\nfor i in range(n - 1):\n    for j in range(n - 1 - i):\n        if numbers[j] > numbers[j + 1]:\n            numbers[j], numbers[j + 1] = numbers[j + 1], numbers[j]\n\nprint(numbers)",
          items: [
          { id: "outer-code", label: "for i in range(n - 1):" },
          { id: "inner-code", label: "for j in range(n - 1 - i):" },
          { id: "condition-code", label: "if numbers[j] > numbers[j + 1]:" },
          { id: "swap-code", label: "numbers[j], numbers[j + 1] = numbers[j + 1], numbers[j]" },
          ],
          targets: [
          { id: "outer-role", label: "一周分の処理を繰り返す" },
          { id: "inner-role", label: "比較位置を右へ動かし、周回ごとに範囲を短くする" },
          { id: "condition-role", label: "左の値が右の値より大きいか確認する" },
          { id: "swap-role", label: "隣り合う2つの値を交換する" },
          ],
          answers: [
          { targetId: "outer-role", itemIds: ["outer-code"] },
          { targetId: "inner-role", itemIds: ["inner-code"] },
          { targetId: "condition-role", itemIds: ["condition-code"] },
          { targetId: "swap-role", itemIds: ["swap-code"] },
          ],
          initialValues: [6, 3, 5, 2],
          resultValues: [2, 3, 5, 6],
          correctFeedback: "Mission 6クリア！バブルソートを構成するすべての処理を組み合わせ、完成コードの役割まで説明できました。次はいよいよCourse完了課題です。",
          incorrectFeedback: "コードを1行ずつ見て、『何を繰り返しているか』『何を判断しているか』を確認してみよう。",
          completionLabel: "Missionを完了",
        },
      },
      preview: null,
      actionLabel: "答えを確認する",
      order: 7,
    },
  ],
};

const courseMission: MissionSeed = {
  id: "bubble-sort-course-mission-v2",
  title: "Course Mission：バブルソートを自分で実装する",
  description: "これまで学んだ比較・交換・繰り返しを使い、バブルソート関数を自分で完成させます。すべてのテストケースを通過するとコースクリアです。",
  difficulty: CourseDifficulty.EASY,
  goalImg: "/images/missions/web-flow.png",
  estimatedMinutes: 15,
  order: 7,
  type: MissionType.COURSE_EXAM,
  isRequiredForCourseCompletion: true,
  parentMissionId: null,
  roadmapLane: 0,
  branchOrder: 0,
  rewardExp: 150,
  learnedItems: ["バブルソートの自力実装", "テスト結果を使った修正", "比較・交換・繰り返しの統合"],
  isPublished: true,
  activities: [
      {
        id: "bubble-sort-course-mission-v2-implementation",
        type: MissionActivityType.TRY_CODE,
        title: "バブルソートを自分で実装しよう",
        instruction: "bubble_sort(numbers) を完成させ、受け取った整数のリストを昇順に並べ替えて返しましょう。",
        mentorMessage: "分からないところがあったら、右のヒントを一つずつ開いてみよう。ここまでの知識で完成できるよ！",
        content: {
          learningRole: "COURSE_EXAM",
          rendererKey: "CODE_EDITOR",
          feedbackPolicy: { mode: "RETRY_WITH_HINT", revealAfterAttempts: 2 },
          data: {
            evaluationMode: "TEST_CASES",
            courseResult: {
            masteryTitle: "バブルソートをマスター",
            description: "バブルソートコースをすべて修了しました。",
            learningOutcome: "バブルソートを実装できるようになりました。",
            },
            body: "関数名と引数はそのまま使います。関数の中に、比較・交換・繰り返しを書いてください。早期終了の最適化は必要ありません。",
            starterCode: `def bubble_sort(numbers):
            # ここにバブルソートの処理を書こう
            pass`,
            testCases: [
            { id: "basic-1", label: "基本ケース 1", input: [5, 2, 4, 1], expected: [1, 2, 4, 5] },
            { id: "basic-2", label: "基本ケース 2", input: [8, 3, 6, 2, 7], expected: [2, 3, 6, 7, 8] },
            { id: "duplicates", label: "重複を含むケース", input: [4, 2, 4, 1, 2], expected: [1, 2, 2, 4, 4] },
            { id: "reverse", label: "逆順ケース", input: [9, 7, 5, 3, 1], expected: [1, 3, 5, 7, 9] },
            { id: "boundary", label: "境界ケース", input: [], expected: [] },
            ],
            hints: [
            {
            id: "compare",
            title: "隣り合う値を比べる",
            body: "比較する位置を j とすると、左は numbers[j]、右は numbers[j + 1] です。左の値が大きいときだけ交換します。",
            code: "if numbers[j] > numbers[j + 1]:",
            },
            {
            id: "swap",
            title: "左右の値を交換する",
            body: "右の値を左へ、左の値を右へ入れます。Pythonでは1行で2つの値を交換できます。",
            code: "numbers[j], numbers[j + 1] = numbers[j + 1], numbers[j]",
            },
            {
            id: "inner-loop",
            title: "比較位置を右へ進める",
            body: "内側の for 文で j を動かします。周回が進むほど右側の確定済み範囲を除くことを思い出しましょう。",
            code: "for j in range(n - 1 - i):",
            },
            {
            id: "outer-loop",
            title: "一周分の処理を繰り返す",
            body: "外側の for 文で一周分の処理を繰り返します。最後に並べ替えた numbers を返してください。",
            code: "for i in range(n - 1):\n    ...\nreturn numbers",
            },
            ],
            correctFeedback: "全テストケースを通過しました。学んだ処理を組み合わせて、バブルソートを実装できています。",
            incorrectFeedback: "未通過のテストケースとヒントを確認し、コードを修正しましょう。",
          },
        },
        preview: null,
        actionLabel: "提出する",
        order: 1,
      },
  ],
};

const missions: MissionSeed[] = [missionOne, missionTwo, missionThree, missionFour, missionFive, missionSix];
missions.push(courseMission);

export const bubbleSortCourseSeed: CourseSeed = {
  id: "course-algorithm-bubble-sort-v2",
  title: "バブルソート",
  description: "数値を順番に並べ替えるバブルソートを、配列カードの動きとPythonコードを対応づけながら学ぶコースです。Pythonのリスト、変数、if文、for文、len、rangeを前提に、比較・交換・繰り返し・比較範囲の短縮を段階的に理解し、最後にbubble_sort関数を自分で実装します。",
  difficulty: CourseDifficulty.EASY,
  isInitiallyUnlocked: true,
  isPublished: true,
  version: 2,
  categories: [CourseCategoryType.SORT],
  missions,
};
