import { CourseDifficulty, CreateThemeCategory } from "@prisma/client";

export const createThemeSeed = [
  {
    id: "create-theme-product-card",
    title: "商品カード",
    description: "商品画像、価格、購入ボタンを持つカードUIを作ります。",
    category: CreateThemeCategory.UI,
    difficulty: CourseDifficulty.EASY,
    estimatedMinutes: 45,
    tags: ["UI", "カード", "CSS"],
    defaultThumbnailUrl: "/images/create-themes/product-card.png",
    requirements: ["商品名と価格を表示する", "購入ボタンを配置する", "スマホ幅でも崩れない"],
    challenges: ["セール表示を追加する", "ホバー時の見た目を変える"],
  },
  {
    id: "create-theme-cafe-menu",
    title: "カフェメニュー",
    description: "カテゴリごとにメニューを見やすく並べるページを作ります。",
    category: CreateThemeCategory.HTML_CSS,
    difficulty: CourseDifficulty.EASY,
    estimatedMinutes: 60,
    tags: ["HTML", "CSS", "レイアウト"],
    defaultThumbnailUrl: "/images/create-themes/cafe-menu.png",
    requirements: ["ドリンクとフードを分けて表示する", "価格を表示する", "見出しを付ける"],
    challenges: ["おすすめメニューを強調する", "印刷しても読みやすくする"],
  },
  {
    id: "create-theme-todo-list",
    title: "TODOリスト",
    description: "タスクを追加・完了できる小さなアプリを作ります。",
    category: CreateThemeCategory.JAVASCRIPT,
    difficulty: CourseDifficulty.NORMAL,
    estimatedMinutes: 90,
    tags: ["JavaScript", "フォーム", "状態管理"],
    defaultThumbnailUrl: "/images/create-themes/todo-list.png",
    requirements: ["タスクを追加できる", "完了状態を切り替えられる", "空の入力を防ぐ"],
    challenges: ["削除機能を追加する", "ローカル保存する"],
  },
  {
    id: "create-theme-quiz-app",
    title: "クイズアプリ",
    description: "選択肢を押して正誤を確認できるクイズを作ります。",
    category: CreateThemeCategory.JAVASCRIPT,
    difficulty: CourseDifficulty.NORMAL,
    estimatedMinutes: 90,
    tags: ["JavaScript", "クイズ", "イベント"],
    defaultThumbnailUrl: "/images/create-themes/quiz-app.png",
    requirements: ["問題文を表示する", "選択肢を表示する", "回答後に正誤を表示する"],
    challenges: ["スコアを表示する", "複数問を切り替える"],
  },
  {
    id: "create-theme-search-filter",
    title: "検索フィルターUI",
    description: "入力した文字で一覧を絞り込むUIを作ります。",
    category: CreateThemeCategory.DATA_DISPLAY,
    difficulty: CourseDifficulty.NORMAL,
    estimatedMinutes: 80,
    tags: ["検索", "一覧", "JavaScript"],
    defaultThumbnailUrl: "/images/create-themes/search-filter.png",
    requirements: ["検索入力を用意する", "一覧を表示する", "入力に合わせて絞り込む"],
    challenges: ["カテゴリフィルターを追加する", "該当なし表示を作る"],
  },
  {
    id: "create-theme-user-list",
    title: "ユーザー一覧ページ",
    description: "複数のユーザー情報を表やカードで表示します。",
    category: CreateThemeCategory.DATA_DISPLAY,
    difficulty: CourseDifficulty.EASY,
    estimatedMinutes: 60,
    tags: ["一覧", "カード", "テーブル"],
    defaultThumbnailUrl: "/images/create-themes/user-list.png",
    requirements: ["名前と役割を表示する", "3人以上のデータを表示する", "情報を読みやすく整える"],
    challenges: ["ステータス表示を追加する", "並び替えを追加する"],
  },
  {
    id: "create-theme-product-search",
    title: "商品検索画面",
    description: "商品一覧、検索、絞り込みを組み合わせた画面を作ります。",
    category: CreateThemeCategory.FORM,
    difficulty: CourseDifficulty.NORMAL,
    estimatedMinutes: 100,
    tags: ["検索", "フォーム", "商品"],
    defaultThumbnailUrl: "/images/create-themes/product-search.png",
    requirements: ["商品一覧を表示する", "キーワード検索できる", "カテゴリで絞り込める"],
    challenges: ["価格帯フィルターを追加する", "検索条件をリセットできる"],
  },
  {
    id: "create-theme-mini-board",
    title: "掲示板ミニアプリ",
    description: "短い投稿を追加して一覧表示するミニ掲示板を作ります。",
    category: CreateThemeCategory.CRUD,
    difficulty: CourseDifficulty.NORMAL,
    estimatedMinutes: 120,
    tags: ["CRUD", "フォーム", "掲示板"],
    defaultThumbnailUrl: "/images/create-themes/mini-board.png",
    requirements: ["投稿フォームを作る", "投稿を一覧に追加する", "投稿日時を表示する"],
    challenges: ["投稿を削除できる", "入力文字数を制限する"],
  },
  {
    id: "create-theme-cocktail-search",
    title: "カクテルレシピ検索UI",
    description: "レシピ情報を検索し、材料や作り方を表示します。",
    category: CreateThemeCategory.API,
    difficulty: CourseDifficulty.HARD,
    estimatedMinutes: 150,
    tags: ["API", "検索", "レシピ"],
    defaultThumbnailUrl: "/images/create-themes/cocktail-search.png",
    requirements: ["検索フォームを作る", "レシピカードを表示する", "材料を読みやすく表示する"],
    challenges: ["外部APIと連携する", "お気に入り表示を追加する"],
  },
  {
    id: "create-theme-high-card-game",
    title: "ハイカードゲーム",
    description: "カードを引いて数字の大小を比べるシンプルなゲームを作ります。",
    category: CreateThemeCategory.GAME,
    difficulty: CourseDifficulty.HARD,
    estimatedMinutes: 150,
    tags: ["ゲーム", "JavaScript", "ランダム"],
    defaultThumbnailUrl: "/images/create-themes/high-card-game.png",
    requirements: ["カードを1枚引ける", "相手カードと比較する", "勝敗を表示する"],
    challenges: ["連勝数を表示する", "カード演出を追加する"],
  },
] as const;
